baseurl = "https://www.enterpriseready.io"
languageCode = "en-us"
title = "EnterpriseReady"
theme = "hugo-theme-enterpriseready"
metadataformat = "yaml"

[taxonomies]
feature = "features"

[params]
  description = "EnterpriseReady"
  ogimage = "https://www.enterpriseready.io/images/enterprise-ready-logo.png"
  copyright = "Replicated, Inc."
  edit_link = "https://github.com/enterpriseready/enterpriseready/edit/master/docs/"
  search = true
  contributor ="Replicated"
  contributorurl = "https://www.replicated.com"

  matomo_host = "data-2.replicated.com"
  matomo_site = "4"
